import { AIService } from '../ai/ai.service';

export interface PlagiarismReport {
    similarityScore: number;
    analysis: string;
    flaggedSegments: {
        text: string;
        reason: string;
    }[];
}

export class PlagiarismService {
    /**
     * Analyzes student submission content for originality and potential AI generation.
     */
    static async checkOriginality(content: string): Promise<PlagiarismReport> {
        if (!content || content.trim().length < 50) {
            return {
                similarityScore: 0,
                analysis: "Content too short for reliable analysis.",
                flaggedSegments: []
            };
        }

        const prompt = `
      You are an expert academic integrity AI. Your task is to analyze the following student submission for originality.
      Assess the likelihood that the content was generated by an AI (like ChatGPT, Claude, etc.) or copied from external sources.
      
      Submission Content:
      "${content.substring(0, 15000)}"
      
      Provide a rigorous analysis. Be specific about stylistic markers, repetitive structures, or unusually perfect grammar/vocabulary 
      that often characterize AI output.
      
      Return the result strictly as a valid JSON object with this exact structure:
      {
        "similarityScore": <number between 0 and 100, where 100 means high confidence of non-originality>,
        "analysis": "<A comprehensive paragraph explaining your findings and specific markers identified>",
        "flaggedSegments": [
          {
            "text": "<The specific snippet of text>",
            "reason": "<Specific reason why this snippet is suspicious>"
          }
        ]
      }
    `;

        try {
            const response = await AIService.chatWithContext(prompt, [
                "Perform deep originality analysis on student work.",
                "Detect AI-generated patterns and stylistic markers.",
                "Identify potential plagiarism segments."
            ]);

            // Clean the response from markdown blocks if present
            const jsonStr = response.replace(/```json|```/g, "").trim();
            const report: PlagiarismReport = JSON.parse(jsonStr);

            // Sanity checks
            if (typeof report.similarityScore !== 'number') report.similarityScore = 0;
            if (!Array.isArray(report.flaggedSegments)) report.flaggedSegments = [];

            return report;
        } catch (error) {
            console.error("[PlagiarismService] Error:", error);
            return {
                similarityScore: 0,
                analysis: "AI analysis failed temporarily. Please try again later.",
                flaggedSegments: []
            };
        }
    }
}
